version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: samurai_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: samurai_db
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped 